services:
  postgresql:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USERNAME : postgres
      POSTGRES_PASSWORD : root
    volumes:
      - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql/data:/var/lib/postgresql/data
