server:
  port: 8088

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: product
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
        - id: inventory
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


